//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneClickN1.AppResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OneClickN1.AppResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        internal static string placeHolderText {
            get {
                return ResourceManager.GetString("placeHolderText", resourceCulture);
            }
        }
        
        internal static string descriptionText {
            get {
                return ResourceManager.GetString("descriptionText", resourceCulture);
            }
        }
        
        internal static string newsN1Button {
            get {
                return ResourceManager.GetString("newsN1Button", resourceCulture);
            }
        }
        
        internal static string telegramButton {
            get {
                return ResourceManager.GetString("telegramButton", resourceCulture);
            }
        }
        
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        internal static string searchAnotherNewsPlaceholder {
            get {
                return ResourceManager.GetString("searchAnotherNewsPlaceholder", resourceCulture);
            }
        }
        
        internal static string loadMoreNewsButton {
            get {
                return ResourceManager.GetString("loadMoreNewsButton", resourceCulture);
            }
        }
        
        internal static string backButton {
            get {
                return ResourceManager.GetString("backButton", resourceCulture);
            }
        }
    }
}
